<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
=======
import "./globals.css";
import Navbar from "../components/navbar";
import { CartProvider } from "./context/CartContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      {/* Tambahkan m-0 p-0 overflow-x-hidden agar tidak ada whitespace/gap samping */}
      <body className="bg-white w-full min-h-screen m-0 p-0 overflow-x-hidden font-sans text-gray-900 antialiased">
        <CartProvider>
          <Navbar />

          {/* KUNCI: main diberi class w-full min-h-screen agar konten di dalamnya melebar 100% */}
          <main className="w-full min-h-screen m-0 p-0">{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
>>>>>>> fb772c414c78a934e9b4b121ed184ef285537f53
